### ISSUE TITLE
Loosen strictness of peer dependency requirement of `tslib`

### ISSUE THREAD

**Issue by mcmxcdev** [LironHazan/nx-size-limit#30]
According to pnpm, this project requires an exact version of tslib (2.5.0) but we are already using a newer patch version:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ nx-size-limit 2.0.1
  └── ✕ unmet peer tslib@2.5.0: found 2.5.2
```

It would be great to change this to either allow the whole major version (v2) or at least all versions of the same minor version (v2.5.x).

**Comment by LironHazan** [comment]
Hey, @mcmxcdev thanks!
The plugin dependency is actually `^2.3.0` (requires by the @nrwl/devkit that the plugin uses and comes with it when using NX to generate a plugin at least currently) so I'm not 100% sure where 2.5.0 is coming from,
I see the size-limit lib itself is [locked on this specific version](https://github.com/ai/size-limit/blob/main/pnpm-lock.yaml#L5153) but I don't know if that's causing the issue (peer of a peer)
I you want you can open a PR to this repo and if all tests will pass in CI I can merge and publish a new version

**Comment by mcmxcdev** [comment]
Hmmm, this is what my pnpm lockfile shows me:

```
  /nx-size-limit@2.0.1(tslib@2.5.2):
    resolution: {integrity: sha512-UccMzNJxHTIPPJEQE564yBVW+hXzaur3XutRo6g9tNW5up7g7CF16EhW5oRDrgIYWcui8bjTepY6gwTFfSsARQ==}
    peerDependencies:
      tslib: 2.5.0
    dependencies:
      '@swc/helpers': 0.5.0
      ts-pattern: 4.2.2
      tslib: 2.5.2
    dev: true
```

I will also investigate further and find out where we need to update this!

**Comment by mcmxcdev** [comment]
Looking at https://www.npmjs.com/package/nx-size-limit?activeTab=code, this repository is setting `tslib` as `peerDependencies` and not `size-limit` or their 3rd party dependencies. But when checking out the `package.json` on the main branch here, it doesn't have that `peerDependencies` set: https://github.com/LironHazan/nx-size-limit/blob/main/package.json

It seems like this repository is out-of-sync with the version that is on npm, needs to be solved.

**Comment by mcmxcdev** [comment]
Whoever is also affected by this:
We have strict [peer dependencies](https://pnpm.io/npmrc#strict-peer-dependencies) set, so I am working around it for now:

```
 "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "tslib": "^2.5.0"
      }
    }
  }
```

Needs to be solved by @LironHazan

**Comment by LironHazan** [comment]
@mcmxcdev Hey sorry I was loaded in work this week and just noticed your comment, feel free to open a PR and I'll merge, else I could only update the project on Friday most likely.

**Comment by mcmxcdev** [comment]
No worries! I cannot provide a PR, because this is nothing that I can fix. Published npm version !== GitHub latest version, so that needs to be synced up. 

You should probably release a v2.0.2 or v2.1.0 depending on what changes you want to include in a new version to refresh the npm database.

**Comment by LironHazan** [comment]
@mcmxcdev I bumped up the version :D
