### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [LironHazan/nx-size-limit#33]
This plugin doesn't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugin doesn't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

**Comment by LironHazan** [comment]
@isaacplmann Hey thanks! pushing a fix
